'''ESCAPING_SEQUENCES'''

# print('hello \apython')
# print('hello \bpython')
# print('hello \cpython')
# print('hello \dpython')
# print('hello \epython')
# print('hello \fpython')
# print('hello \gpython')
# print('hello \hpython')
# print('hello \ipython')
# print('hello \jpython')
# print('hello \kpython')
# print('hello \lpython')
# print('hello \mpython')
# print('hello \npython')
# print('hello \opython')
# print('hello \ppython')
# print('hello \qpython')
# print('hello \rpython')
# print('hello \spython')
# print('hello \tpython')
# print('hello \upython')
# print('hello \vpython')
# print('hello \wpython')
# print('hello \xpython')
# print('hello \ypython')
# print('hello \zpython')

# print('hello \Apython')
# print('hello \Bpython')
# print('hello \Cpython')
# print('hello \Dpython')
# print('hello \Epython')
# print('hello \Fpython')
# print('hello \Gpython')
# print('hello \Hpython')
# print('hello \Ipython')
# print('hello \Jpython')
# print('hello \Kpython')
# print('hello \Lpython')
# print('hello \Mpython')
# # print('hello \Npython')
# print('hello \Opython')
# print('hello \Ppython')
# print('hello \Qpython')
# print('hello \Rpython')
# print('hello \Spython')
# print('hello \Tpython')
# # print('hello \Upython')
# print('hello \Vpython')
# print('hello \Wpython')
# print('hello \Xpython')
# print('hello \Ypython')
# print('hello \Zpython')